HR_ADMIN = "HR Admin"
HR_MANAGER = "HR Manager"
HR_PAYROLL_ADMIN = "HR Payroll Admin"
HR_REPORTING_MANAGER = "HR Reporting Manager"
HR_EMPLOYEE = "HR Employee"
SYSTEM_MANAGER = "System Manager"

HR_ROLES = (
	HR_ADMIN,
	HR_MANAGER,
	HR_PAYROLL_ADMIN,
	HR_REPORTING_MANAGER,
	HR_EMPLOYEE,
)

STAFF_ROLES = (HR_ADMIN, HR_MANAGER, HR_PAYROLL_ADMIN, HR_REPORTING_MANAGER, SYSTEM_MANAGER)

# Roles that can open the /hr SPA.
APP_ROLES = (*HR_ROLES, SYSTEM_MANAGER)

# Org-wide employee directory (not own-record only).
DIRECTORY_ROLES = (HR_ADMIN, HR_MANAGER, HR_PAYROLL_ADMIN, SYSTEM_MANAGER)

# Can create / deactivate employees.
EMPLOYEE_WRITE_ROLES = (HR_ADMIN, HR_MANAGER, SYSTEM_MANAGER)

# Bank / PAN / Aadhaar / UAN / ESI / PF (permlevel 1).
PII_READ_ROLES = (HR_ADMIN, HR_PAYROLL_ADMIN, SYSTEM_MANAGER)

# Salary structures, payroll runs, payslips, bank CSV, audit log.
PAYROLL_ADMIN_ROLES = (HR_ADMIN, HR_PAYROLL_ADMIN, SYSTEM_MANAGER)
