/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Layouts/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/Layouts/AppSidebar.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DashboardAdminQueues: typeof import('./src/components/DashboardAdminQueues.vue')['default']
    DashboardHome: typeof import('./src/components/DashboardHome.vue')['default']
    DataList: typeof import('./src/components/DataList.vue')['default']
    DesktopLayout: typeof import('./src/components/Layouts/DesktopLayout.vue')['default']
    FormAlerts: typeof import('./src/components/FormAlerts.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    PageContent: typeof import('./src/components/PageContent.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
    ViewBreadcrumbs: typeof import('./src/components/ViewBreadcrumbs.vue')['default']
  }
}
